"""
ClaudeMdEnhancer — auto-detect project conventions for LLM.md generation.

Ported from the ClaudeMdEnhancer class in llm-context-setup.py.
Detects: error handling patterns, test frameworks, async usage, ORM,
API style, logging libraries, dangerous files, and code quality tools.
"""

import ast
import json
import re
from pathlib import Path
from typing import Dict, List, Optional

from ..models import ProjectInfo
from ..utils.files import safe_read_text, should_skip_path


class ClaudeMdEnhancer:
    """Auto-detect conventions and generate an enhanced LLM.md."""

    def __init__(self, root: Path):
        self.root = root

    # ── Public interface ──────────────────────────────────────────────────────

    def detect_conventions(self) -> dict:
        """Detect all project conventions. Returns a dict of findings."""
        return {
            "error_handling": self._detect_error_pattern(),
            "testing_framework": self._detect_test_framework(),
            "async_pattern": self._detect_async_usage(),
            "orm_pattern": self._detect_orm(),
            "api_style": self._detect_api_style(),
            "logging_pattern": self._detect_logging(),
            "dangerous_files": self._find_dangerous_files(),
            "code_quality_tools": self._detect_quality_tools(),
        }

    def generate_enhanced_llm_md(self, project: ProjectInfo) -> str:
        """Generate full LLM.md content with auto-detected conventions."""
        conventions = self.detect_conventions()
        test_frameworks = conventions.get("testing_framework", {})
        quality_tools = conventions.get("code_quality_tools", {})

        lines = []
        lines.append(f"# {project.name} — LLM Context")
        lines.append("")
        lines.append("> Auto-generated by CCC. Review and fill in the TODOs.")
        lines.append("")
        lines.append("## Identity")
        lines.append("You are a senior developer on this project with deep knowledge of the codebase.")
        lines.append("")
        lines.append("## Stack")

        if project.languages:
            lines.append(f"- **Languages**: {', '.join(project.languages)}")
        else:
            lines.append("- **Languages**: Unknown")

        lines.append(f"- **Framework**: {project.framework or 'Unknown'}")
        lines.append(f"- **Package Manager**: {project.package_manager or 'Unknown'}")

        if project.python_version:
            lines.append(f"- **Python**: {project.python_version}")

        api_style = conventions.get("api_style", "Unknown")
        lines.append(f"- **API Style**: {api_style}")

        orm = conventions.get("orm_pattern")
        if orm:
            lines.append(f"- **Database**: {orm}")

        logging = conventions.get("logging_pattern")
        if logging:
            lines.append(f"- **Logging**: {logging}")

        if project.has_docker:
            lines.append("- **Containerized**: Docker")

        if project.has_ci:
            lines.append("- **CI/CD**: Configured")

        lines.append("")
        lines.append("## Project Description")
        if project.description:
            lines.append(project.description)
        else:
            lines.append("TODO: Add a one-paragraph description of what this project does.")

        lines.append("")
        lines.append("## Critical Conventions")
        lines.append("")
        lines.append("### Error Handling")
        lines.append(conventions.get("error_handling", "TODO: Document error handling strategy"))

        if test_frameworks:
            lines.append("")
            lines.append("### Testing")
            for lang, framework in test_frameworks.items():
                lines.append(f"- {lang.capitalize()}: {framework}")

        async_pattern = conventions.get("async_pattern")
        if async_pattern:
            lines.append("")
            lines.append("### Async/Await")
            lines.append(async_pattern)

        if quality_tools:
            lines.append("")
            lines.append("### Code Quality")
            if quality_tools.get("linters"):
                lines.append(f"- Linters: {', '.join(quality_tools['linters'])}")
            if quality_tools.get("formatters"):
                lines.append(f"- Formatters: {', '.join(quality_tools['formatters'])}")
            if quality_tools.get("type_checkers"):
                lines.append(f"- Type checking: {', '.join(quality_tools['type_checkers'])}")

        lines.append("")
        lines.append("### Code Style")
        lines.append("- TODO: Max function length?")
        lines.append("- TODO: Naming conventions?")
        lines.append("- TODO: Import organization?")

        dangerous_files = conventions.get("dangerous_files", [])
        if dangerous_files:
            lines.append("")
            lines.append("## Dangerous Areas")
            lines.append("<!-- These files contain sensitive logic. Extra care required. -->")
            lines.append("")
            for item in dangerous_files[:5]:
                reasons = " | ".join(item["reasons"])
                lines.append(f"- **`{item['file']}`** — {reasons}")
                lines.append("  - TODO: Add specific gotchas")

        lines.append("")
        lines.append("## Current State")
        lines.append("<!-- TODO: What's in progress? What's deprecated? -->")
        lines.append("- TODO: Any ongoing migrations or refactors?")
        lines.append("- TODO: Any deprecated patterns to avoid?")

        lines.append("")
        lines.append("## Common Tasks")
        lines.append("")
        lines.append("### Running the Project")
        lines.append("```bash")
        lines.append("# TODO: How to start development")
        lines.append("# TODO: How to run tests")
        lines.append("# TODO: How to build for production")
        lines.append("```")

        lines.append("")
        lines.append("### Adding New Features")
        lines.append("TODO: Step-by-step guide for common additions")

        lines.append("")
        lines.append("## Common Gotchas")
        lines.append("<!-- Things that aren't obvious from reading the code -->")
        lines.append("- TODO: Race conditions to watch for?")
        lines.append("- TODO: Order-dependent operations?")
        lines.append("- TODO: Performance bottlenecks?")

        lines.append("")
        lines.append("## Generated Context")
        lines.append("")
        lines.append("See `.llm-context/` for auto-extracted context:")
        lines.append("- `tree.txt` — structure")
        lines.append("- `routes.txt` — API routes")
        lines.append("- `schemas-extracted.*` — type definitions")
        lines.append("- `symbol-index.json` — symbol → file:line map")
        lines.append("- `external-dependencies.json` — service boundary contracts")
        lines.append("")

        return "\n".join(lines)

    # ── Detection methods ─────────────────────────────────────────────────────

    def _detect_error_pattern(self) -> str:
        """Detect error handling pattern (Result type vs exceptions)."""
        py_files = list(self.root.rglob("*.py"))[:20]
        result_count = 0
        exception_count = 0

        for f in py_files:
            if should_skip_path(f):
                continue
            content = safe_read_text(f)
            if not content:
                continue
            if "Result[" in content or "from result import" in content:
                result_count += 1
            exception_count += content.count("raise ")

        if result_count > 5:
            return "Result pattern (functional error handling)"
        elif exception_count > 20:
            return "Exception-based (try/except)"
        return "Mixed/unclear (TODO: document your strategy)"

    def _detect_test_framework(self) -> Dict[str, str]:
        """Detect test frameworks per language."""
        frameworks: Dict[str, str] = {}

        # Python: check config files first
        if (self.root / "pytest.ini").exists():
            frameworks["python"] = "pytest"
        else:
            pyproject = self.root / "pyproject.toml"
            if pyproject.exists():
                content = safe_read_text(pyproject) or ""
                if "pytest" in content:
                    frameworks["python"] = "pytest"

        # Python: fallback — scan test files
        if not frameworks.get("python"):
            for tf in list(self.root.rglob("test_*.py"))[:5]:
                content = safe_read_text(tf) or ""
                if "import pytest" in content:
                    frameworks["python"] = "pytest"
                    break
                if "import unittest" in content:
                    frameworks["python"] = "unittest"
                    break

        # JavaScript/TypeScript: check package.json
        package_json = self.root / "package.json"
        if package_json.exists():
            content = safe_read_text(package_json)
            if content:
                try:
                    pkg = json.loads(content)
                    deps: dict = {}
                    deps.update(pkg.get("dependencies", {}))
                    deps.update(pkg.get("devDependencies", {}))
                    if "jest" in deps:
                        frameworks["javascript"] = "jest"
                    elif "vitest" in deps:
                        frameworks["javascript"] = "vitest"
                    elif "mocha" in deps:
                        frameworks["javascript"] = "mocha"
                except Exception:
                    pass

        return frameworks

    def _detect_async_usage(self) -> Optional[str]:
        """Detect async/await usage ratio in Python files."""
        py_files = list(self.root.rglob("*.py"))[:30]
        async_count = 0
        total_functions = 0

        for f in py_files:
            if should_skip_path(f):
                continue
            content = safe_read_text(f)
            if not content:
                continue
            try:
                tree = ast.parse(content)
                for node in ast.walk(tree):
                    if isinstance(node, ast.FunctionDef):
                        total_functions += 1
                    elif isinstance(node, ast.AsyncFunctionDef):
                        async_count += 1
                        total_functions += 1
            except Exception:
                continue

        if total_functions == 0:
            return None

        ratio = async_count / total_functions
        if ratio > 0.3:
            return f"Heavy async (~{int(ratio * 100)}% of functions)"
        elif ratio > 0.1:
            return "Mixed sync/async"
        return None

    def _detect_orm(self) -> Optional[str]:
        """Detect ORM or database layer."""
        orms: List[str] = []

        for config_file in ["requirements.txt", "pyproject.toml"]:
            path = self.root / config_file
            if path.exists():
                content = (safe_read_text(path) or "").lower()
                if "sqlalchemy" in content:
                    orms.append("SQLAlchemy")
                if "django" in content:
                    orms.append("Django ORM")
                if "tortoise" in content:
                    orms.append("Tortoise ORM")

        package_json = self.root / "package.json"
        if package_json.exists():
            content = safe_read_text(package_json)
            if content:
                try:
                    pkg = json.loads(content)
                    deps: dict = {}
                    deps.update(pkg.get("dependencies", {}))
                    deps.update(pkg.get("devDependencies", {}))
                    if "typeorm" in deps:
                        orms.append("TypeORM")
                    if "prisma" in deps:
                        orms.append("Prisma")
                    if "sequelize" in deps:
                        orms.append("Sequelize")
                    if "mongoose" in deps:
                        orms.append("Mongoose")
                except Exception:
                    pass

        return ", ".join(orms) if orms else None

    def _detect_api_style(self) -> str:
        """Detect API style: REST, GraphQL, gRPC."""
        styles: List[str] = []

        # GraphQL: look for schema files
        for gf in ["schema.graphql", "schema.gql"]:
            if (self.root / gf).exists():
                styles.append("GraphQL")
                break

        # GraphQL / gRPC: check dependency files
        for dep_file in ["requirements.txt", "pyproject.toml", "package.json"]:
            path = self.root / dep_file
            if path.exists():
                content = (safe_read_text(path) or "").lower()
                if "graphql" in content and "GraphQL" not in styles:
                    styles.append("GraphQL")
                if ("grpc" in content or "protobuf" in content) and "gRPC" not in styles:
                    styles.append("gRPC")

        # REST: look for route decorators in Python
        route_count = 0
        for py_file in list(self.root.rglob("*.py"))[:20]:
            if should_skip_path(py_file):
                continue
            content = safe_read_text(py_file) or ""
            if re.search(r"@(?:app|router)\.(get|post|put|delete)", content):
                route_count += 1
                if route_count >= 3:
                    styles.insert(0, "REST")
                    break

        return " + ".join(styles) if styles else "REST (assumed)"

    def _detect_logging(self) -> Optional[str]:
        """Detect logging framework."""
        logging_libs: set = set()

        for f in list(self.root.rglob("*.py"))[:20]:
            if should_skip_path(f):
                continue
            content = safe_read_text(f) or ""
            if "import logging" in content:
                logging_libs.add("stdlib logging")
            if "from loguru import" in content:
                logging_libs.add("loguru")
            if "import structlog" in content:
                logging_libs.add("structlog")

        return ", ".join(logging_libs) if logging_libs else None

    def _find_dangerous_files(self) -> List[dict]:
        """Find files that contain sensitive or high-risk logic."""
        dangerous: List[dict] = []

        danger_keywords = {
            "payment": "Payment processing",
            "billing": "Billing logic",
            "auth": "Authentication",
            "password": "Password handling",
            "crypto": "Cryptography",
            "encrypt": "Encryption",
            "private_key": "Private key usage",
            "migration": "Database migration",
        }

        for py_file in self.root.rglob("*.py"):
            if should_skip_path(py_file):
                continue
            content = safe_read_text(py_file)
            if not content:
                continue
            content_lower = content.lower()
            matches = [
                description
                for keyword, description in danger_keywords.items()
                if keyword in content_lower
            ]
            if matches:
                try:
                    rel_path = str(py_file.relative_to(self.root))
                    dangerous.append({"file": rel_path, "reasons": matches})
                except Exception:
                    pass

        # Sort by number of danger signals descending, return top 10
        dangerous.sort(key=lambda x: len(x["reasons"]), reverse=True)
        return dangerous[:10]

    def _detect_quality_tools(self) -> Dict[str, List[str]]:
        """Detect linters, formatters, and type checkers."""
        tools: Dict[str, List[str]] = {
            "linters": [],
            "formatters": [],
            "type_checkers": [],
        }

        for config_file in ["pyproject.toml", "setup.cfg", ".flake8", "tox.ini"]:
            path = self.root / config_file
            if not path.exists():
                continue
            content = safe_read_text(path) or ""
            if "ruff" in content and "ruff" not in tools["linters"]:
                tools["linters"].append("ruff")
            if "flake8" in content and "flake8" not in tools["linters"]:
                tools["linters"].append("flake8")
            if "pylint" in content and "pylint" not in tools["linters"]:
                tools["linters"].append("pylint")
            if "black" in content and "black" not in tools["formatters"]:
                tools["formatters"].append("black")
            if "isort" in content and "isort" not in tools["formatters"]:
                tools["formatters"].append("isort")
            if "mypy" in content and "mypy" not in tools["type_checkers"]:
                tools["type_checkers"].append("mypy")
            if "pyright" in content and "pyright" not in tools["type_checkers"]:
                tools["type_checkers"].append("pyright")

        package_json = self.root / "package.json"
        if package_json.exists():
            content = safe_read_text(package_json)
            if content:
                try:
                    pkg = json.loads(content)
                    deps: dict = {}
                    deps.update(pkg.get("dependencies", {}))
                    deps.update(pkg.get("devDependencies", {}))
                    if "eslint" in deps:
                        tools["linters"].append("eslint")
                    if "prettier" in deps:
                        tools["formatters"].append("prettier")
                    if "typescript" in deps:
                        tools["type_checkers"].append("tsc")
                except Exception:
                    pass

        # Return only populated categories
        return {k: v for k, v in tools.items() if v}
